resources:
- repo: self
trigger:
  branches:
    include:
    - '*'

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      sysctl kern.hv_support
      sysctl machdep.cpu.features
    displayName: List CPU features

  - script: |
      sudo ls
      echo "Downloading DMG."
      curl -Lo docker.dmg https://download.docker.com/mac/edge/41561/Docker.dmg
      echo "Extract DMG."
      hdiutil attach docker.dmg
      (cd /Volumes/Docker/ ; cp -av Docker.app /Applications/Docker.app)
      hdiutil detach /Volumes/Docker/
      echo "Install Docker."
      sudo /Applications/Docker.app/Contents/MacOS/Docker --quit-after-install --unattended || true

    displayName: Install Docker Desktop

  - script: |
      echo "Start Docker."
      sh -c "sudo /Applications/Docker.app/Contents/MacOS/Docker --install-privileged-components --unattended" &
      echo "Wait a little bit..."
      sleep 200
      ps -ef
      ls -l /Applications/Docker.app/Contents/Resources/bin/docker
      sudo /Applications/Docker.app/Contents/Resources/bin/docker version
      sudo /Applications/Docker.app/Contents/Resources/bin/docker run hello-world
      sudo /Applications/Docker.app/Contents/Resources/bin/docker images

    displayName: Start Docker

  - script: |
      sudo docker build -t test .
      sudo docker run test

    displayName: Build and run container