resources:
- repo: self
trigger:
  branches:
    include:
    - '*'

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      sysctl kern.hv_support
      sysctl machdep.cpu.features
    displayName: List CPU features

  - script: |
      sudo ls
      echo "Downloading DMG."
      curl -Lo docker.dmg https://download.docker.com/mac/stable/28905/Docker.dmg
      echo "Extract DMG."
      hdiutil attach docker.dmg
      (cd /Volumes/Docker/ ; cp -av Docker.app /Applications/Docker.app)
      hdiutil detach /Volumes/Docker/
      echo "Install Docker."
      sudo /Applications/Docker.app/Contents/MacOS/Docker --quit-after-install --unattended

    displayName: Install Docker Desktop

  - script: |
      echo "Start Docker."
      sh -c "sudo /Applications/Docker.app/Contents/MacOS/Docker --install-privileged-components --unattended" &
      echo "Wait a little bit..."
      sleep 100
      sudo docker version
      sudo docker run hello-world
      sudo docker images

    displayName: Run Docker Desktop

  - script: |
      sudo docker build -t test .
      sudo docker run test

    displayName: Run Docker Desktop