resources:
- repo: self
trigger:
  branches:
    include:
    - '*'

jobs:
- job: Windows1803
  pool:
    vmImage: 'win1803'
  steps:
  - powershell: |
      Get-Service
    displayName: 'List services'
  - powershell: |
      Get-WindowsFeature
    displayName: 'List Windows features'

- job: Windows1803
  pool:
    vmImage: 'win1803'
  steps:
  - powershell: |
      Get-Service
    displayName: 'List services'
  - powershell: |
      Get-WindowsFeature
    displayName: 'List Windows features'

- job: Windows2016
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
      Get-Service
    displayName: 'List services'
  - powershell: |
      Get-WindowsFeature
    displayName: 'List Windows features'

- job: Windows2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - powershell: |
      Get-Service
    displayName: 'List services'
  - powershell: |
      Get-WindowsFeature
    displayName: 'List Windows features'
