resources:
- repo: self
trigger:
- master
queue:
  name: Hosted Windows Container
steps:
- script: |
   docker version
   docker info
   docker images
   
  displayName: 'Run some docker commands'
- script: |
   docker build -t test .
   
  displayName: 'Build image'
- script: |
   docker run test
   
  displayName: 'Test image'
