resources:
- repo: self
trigger:
  branches:
    include:
    - '*'

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      echo hello from macOS
      uname -a
    description: Run on macOS 10.14

