resources:
- repo: self
trigger:
  branches:
    include:
    - '*'

jobs:
- job: LinuxAMD64
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
    env:
      DOCKER_USER: $(DOCKER_USER)
      DOCKER_PASS: $(DOCKER_PASS)
    displayName: 'Docker push'

- job: Windows2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - powershell: |
      docker login --username "$env:DOCKER_USER" --password "$env:DOCKER_PASS"
    env:
      DOCKER_USER: $(DOCKER_USER)
      DOCKER_PASS: $(DOCKER_PASS)
    displayName: 'Docker push'
