resources:
- repo: self
trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      echo hello from Linux
      uname -a
      dpkg -l
    displayName: 'Check agent'
  - script: |
      docker version
      docker info
      docker images
    displayName: 'Check Docker'
  - script: |
      docker run hello-world
    displayName: 'Run hello-world'
  - script: |
      docker run mplatform/mquery golang:1.12.2
    displayName: 'Run mplatform/mquery golang:1.12.2'
  - script: |
      docker build -t hello:linux .
    displayName: 'Build image'
  - script: |
      docker run hello:linux
    displayName: 'Test image'

# - job: macOS
#   pool:
#     vmImage: 'macOS-10.14'
#   steps:
#   - script: |
#       echo hello from macOS
#       uname -a
#     displayName: 'Check agent'
#   # Docker is not installed on macOS agent
#   - script: |
#       docker version
#     displayName: 'Check Docker'

- job: Windows1803
  pool:
    vmImage: 'win1803'
  steps:
  - script: |
      echo hello from Windows
      ver
    displayName: 'Check agent'
  - script: |
      docker version
      docker info
      docker images
    displayName: 'Check Docker'
#   - script: |
#       docker run hello-world
#     displayName: 'Run hello-world'
#   - script: |
#       docker run --isolation=hyperv mplatform/mquery golang:1.12.2
#     displayName: 'Run --isolation=hyperv mplatform/mquery golang:1.12.2'
  - script: |
      docker build -t hello:windows-1803 .
    displayName: 'Build image'
  - script: |
      docker run hello:windows-1803
    displayName: 'Test image'

- job: Windows2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      echo hello from Windows
      ver
    displayName: 'Check agent'
  - script: |
      docker version
      docker info
      docker images
    displayName: 'Check Docker'
#   - script: |
#       docker run hello-world
#     displayName: 'Run hello-world'
#   # hyperv isolation doesn't seem to work on windows-2019 agent
#   - script: |
#       docker run --isolation=hyperv mplatform/mquery golang:1.12.2
#     displayName: 'Run --isolation=hyperv mplatform/mquery golang:1.12.2'
  - script: |
      docker build -t hello:windows-1809 .
    displayName: 'Build image'
  - script: |
      docker run hello:windows-1809
    displayName: 'Test image'
