resources:
- repo: self
trigger:
  branches:
    include:
    - '*'

jobs:
- job: LinuxAMD64
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      echo "$DOCKER_USER"
      echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
    env:
      DOCKER_USER: $(DOCKER_USER)
      DOCKER_PASS: $(DOCKER_PASS)
    displayName: 'Docker login'


- job: Windows2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - powershell: |
      mkdir ~/.docker
      $auth =[System.Text.Encoding]::UTF8.GetBytes("$($env:DOCKER_USER):$($env:DOCKER_PASS)")
      $auth64 = [Convert]::ToBase64String($auth)
      @"
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "auth": "$auth64"
          }
        }
      }
      "@ | Out-File -Encoding Ascii ~/.docker/config.json
      docker images
      cat ~/.docker/config.json
      docker pull mcr.microsoft.com/windows/nanoserver:1809
      docker tag mcr.microsoft.com/windows/nanoserver:1809 stefanscherer/hello:test
      docker push stefanscherer/hello:test
    env:
      DOCKER_USER: $(DOCKER_USER)
      DOCKER_PASS: $(DOCKER_PASS)
    displayName: 'Docker login'

- job: Windows1803
  pool:
    vmImage: 'win1803'
  steps:
  - powershell: |
      Write-Output $env:DOCKER_PASS | docker login --username $env:DOCKER_USER --password-stdin
    env:
      DOCKERUSER: $(DOCKER_USER)
      DOCKERPASS: $(DOCKER_PASS)
    displayName: 'Docker login'
