resources:
- repo: self
trigger:
  branches:
    include:
    - '*'
  tags:
    include:
      - refs/tags/*

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      printenv
    displayName: 'List env'

- job: Windows2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      set
    displayName: 'List env'
