resources:
- repo: self
trigger:
- mac

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      echo hello from Linux
      uname -a
    displayName: 'Check agent'
  - script: |
      docker version
      docker info
      docker images
      docker run hello-world
    displayName: 'Check Docker'

- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      echo hello from macOS
      uname -a
    displayName: 'Check agent'
  - script: |
      docker version
      docker info
      docker images
      docker run hello-world
    displayName: 'Check Docker'

- job: Windows1803
  pool:
    vmImage: 'win1803'
  steps:
  - script: |
      echo hello from Windows
      ver
    displayName: 'Check agent'
  - script: |
      docker version
      docker info
      docker images
      docker run hello-world
    displayName: 'Check Docker'

- job: Windows2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      echo hello from Windows
      ver
    displayName: 'Check agent'
  - script: |
      docker version
      docker info
      docker images
      docker run hello-world
    displayName: 'Check Docker'
